# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CineFile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CineFile
  pod 'Alamofire', '~> 4.5'
  pod 'SDWebImage', '~> 4.0'

  target 'CineFileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CineFileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
